version: '3.8'

services:
  postgres:
    container_name: postgres-sf
    image: postgres:16-alpine
    network_mode: "host"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      # Используем стандартное имя тома для проекта
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: redis-sf
    image: redis:7-alpine
    network_mode: "host"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq-sf
    image: rabbitmq:3-management-alpine
    #network_mode: "host"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

# Объявляем тома. Docker Compose сам создаст их, если их нет.
volumes:
  postgres_data:
  rabbitmq_data:
