export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EXPIRED_CONFIRMATION_CODE = 'EXPIRED_CONFIRMATION_CODE',
  INVALID_CONFIRMATION_CODE = 'INVALID_CONFIRMATION_CODE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ERROR = 'ERROR',
}
